# Flare table (Table 1 in paper) and electronic version of all confirmed flares

In [2]:
from funcs.notebook import *
from funcs.phaseanalysis import get_flare_phases

rotper =  4.862 # martioli
orbper =  8.463 # exoplanet.eu

In [3]:
aumic1 = pd.read_csv("../results/2021_02_18_AUMic_flares_1.csv")
aumic1 = aumic1[(aumic1.final==1) & (aumic1["real?"]==1)]
aumic27 = pd.read_csv("../results/2021_02_11_AUMic_flares_27.csv")
aumic27 = aumic27[(aumic27.final==1) & (aumic27["real?"]==1)]
aumic_ = pd.concat([aumic1,aumic27])


aumic_.head()

,istart,istop,cstart,cstop,tstart,tstop,ed_rec,ed_rec_err,ampl_rec,dur,total_n_valid_data_points,ID,qcs,mission,tstamp,dur_detrend,lc_n,real?,note,final
6,1509,1519,71983,71993,1327.437532,1327.451421,0.661332,0.038413,0.001381,0.013889,18094,AU Mic,1,TESS,18_02_2021_14_40_23,8.047532,0,1.0,NaN,1.0
7,1532,1539,72006,72013,1327.469477,1327.479199,0.659758,0.044819,0.001441,0.009722,18094,AU Mic,1,TESS,18_02_2021_14_40_23,8.047532,0,1.0,NaN,1.0
8,1818,1827,72313,72322,1327.895864,1327.908364,1.669144,0.039894,0.003435,0.012500,18094,AU Mic,1,TESS,18_02_2021_14_40_23,8.047532,0,1.0,NaN,1.0
9,1997,2004,72492,72499,1328.144475,1328.154197,0.923981,0.045494,0.002392,0.009722,18094,AU Mic,1,TESS,18_02_2021_14_40_23,8.047532,0,1.0,NaN,1.0
11,2254,2278,72751,72775,1328.504196,1328.537529,14.728960,0.035002,0.025630,0.033333,18094,AU Mic,1,TESS,18_02_2021_14_40_23,8.047532,0,1.0,NaN,1.0

In [4]:
aumic_ = get_flare_phases(aumic_, "Orbit")

In [9]:
restab = aumic_[['qcs', 'tstart', 'tstop', 'phases',
                 'ed_rec', 'ed_rec_err', 'ampl_rec']].round(4).sort_values(by="phases")

restab[r"$ED$ [s]"] = restab.apply(lambda x: fr"${x.ed_rec:.2f} \pm {x.ed_rec_err:.2f}$", axis=1)
restab.ampl_rec = restab.ampl_rec.round(3)
restab.phases = restab.phases.round(3)

## branch out electronic table:

In [16]:
restab_electronic = restab.drop("$ED$ [s]", axis=1)
restab_electronic = restab_electronic.rename(index=str, columns={"qcs":"Sec.",
                                           "tstart":r"$t_s$ [BTJD]",
                                           "tstop":r"$t_f$ [BTJD]",
                                           "phases":"orb. phase",
                                           "ampl_rec":r"$a$",
                                           "ed_rec":r"$ED$ [s]",
                                           "ed_rec_err":r"$\sigma_{ED}$ [s]",
                                            })
restab_electronic

,Sec.,$t_s$ [BTJD],$t_f$ [BTJD],orb. phase,$ED$ [s],$\sigma_{ED}$ [s],$a$
167,27,2058.2378,2058.2526,0.001,3.4762,0.0413,0.007
168,27,2058.2584,2058.2593,0.004,0.1026,0.0122,0.002
41,27,2041.3551,2041.3572,0.006,0.2325,0.0197,0.002
20,1,1330.4514,1330.4709,0.007,1.6454,0.0324,0.003
42,27,2041.3690,2041.3734,0.008,0.7045,0.0267,0.003
...,...,...,...,...,...,...,...
209,27,2058.0725,2058.0875,0.982,0.6603,0.0320,0.002
40,27,2041.2065,2041.2100,0.989,0.3974,0.0234,0.002
87,1,1347.2692,1347.2803,0.994,0.9361,0.0699,0.001
92,27,2049.7375,2049.7430,0.997,1.5388,0.0253,0.007
93,27,2049.7539,2049.7555,0.999,0.2041,0.0150,0.002

In [17]:
# save full electronic table
restab_electronic.to_csv("../results/2021_12_AU_Mic_final_flare_table.csv", index=False)

## now reduced version for paper:

In [6]:
del restab["ed_rec"]
del restab["ed_rec_err"]

In [7]:
restab = restab.rename(index=str, columns={"qcs":"Sec.",
                                           "tstart":r"$t_s$ [BTJD]",
                                           "tstop":r"$t_f$ [BTJD]",
                                           "phases":"orb. phase",
                                           "ampl_rec":r"$a$",
                                            })
restab

     Sec.  $t_s$ [BTJD]  $t_f$ [BTJD]  orb. phase    $a$         $ED$ [s]
167    27     2058.2378     2058.2526       0.001  0.007  $3.48 \pm 0.04$
168    27     2058.2584     2058.2593       0.004  0.002  $0.10 \pm 0.01$
41     27     2041.3551     2041.3572       0.006  0.002  $0.23 \pm 0.02$
20      1     1330.4514     1330.4709       0.007  0.003  $1.65 \pm 0.03$
42     27     2041.3690     2041.3734       0.008  0.003  $0.70 \pm 0.03$
..    ...           ...           ...         ...    ...              ...
209    27     2058.0725     2058.0875       0.982  0.002  $0.66 \pm 0.03$
40     27     2041.2065     2041.2100       0.989  0.002  $0.40 \pm 0.02$
87      1     1347.2692     1347.2803       0.994  0.001  $0.94 \pm 0.07$
92     27     2049.7375     2049.7430       0.997  0.007  $1.54 \pm 0.03$
93     27     2049.7539     2049.7555       0.999  0.002  $0.20 \pm 0.01$

[189 rows x 6 columns]

In [14]:
restab = restab[["Sec.",r"$t_s$ [BTJD]", r"$t_f$ [BTJD]", "orb. phase", r"$a$", r"$ED$ [s]"]]

In [15]:
stri = restab.head(10).to_latex(index=False,escape=False, column_format=f"l|ccccc")
stri = stri.replace("\\toprule","\hline")
stri = stri.replace("\\midrule","\hline")
stri = stri.replace("{}","\hline")
stri = stri.replace("\\bottomrule","\hline\n" )
print(stri)

\begin{tabular}{l|ccccc}
\hline
 Sec. &  $t_s$ [BTJD] &  $t_f$ [BTJD] &  orb. phase &    $a$ &         $ED$ [s] \\
\hline
   27 &     2058.2378 &     2058.2526 &       0.001 &  0.007 &  $3.48 \pm 0.04$ \\
   27 &     2058.2584 &     2058.2593 &       0.004 &  0.002 &  $0.10 \pm 0.01$ \\
   27 &     2041.3551 &     2041.3572 &       0.006 &  0.002 &  $0.23 \pm 0.02$ \\
    1 &     1330.4514 &     1330.4709 &       0.007 &  0.003 &  $1.65 \pm 0.03$ \\
   27 &     2041.3690 &     2041.3734 &       0.008 &  0.003 &  $0.70 \pm 0.03$ \\
   27 &     2041.6186 &     2041.6202 &       0.038 &  0.002 &  $0.15 \pm 0.02$ \\
   27 &     2050.1252 &     2050.1259 &       0.043 &  0.003 &  $0.10 \pm 0.01$ \\
   27 &     2050.1724 &     2050.1731 &       0.048 &  0.001 &  $0.07 \pm 0.01$ \\
    1 &     1330.8028 &     1330.8250 &       0.049 &  0.002 &  $1.72 \pm 0.06$ \\
   27 &     2058.7093 &     2058.7148 &       0.057 &  0.004 &  $0.74 \pm 0.03$ \\
\hline

\end{tabular}

<>:2: DeprecationWarning: invalid escape sequence \h
<>:3: DeprecationWarning: invalid escape sequence \h
<>:4: DeprecationWarning: invalid escape sequence \h
<>:5: DeprecationWarning: invalid escape sequence \h
<>:2: DeprecationWarning: invalid escape sequence \h
<>:3: DeprecationWarning: invalid escape sequence \h
<>:4: DeprecationWarning: invalid escape sequence \h
<>:5: DeprecationWarning: invalid escape sequence \h
<>:2: DeprecationWarning: invalid escape sequence \h
<>:3: DeprecationWarning: invalid escape sequence \h
<>:4: DeprecationWarning: invalid escape sequence \h
<>:5: DeprecationWarning: invalid escape sequence \h
<ipython-input-15-5876a08b8638>:2: DeprecationWarning: invalid escape sequence \h
  stri = stri.replace("\\toprule","\hline")
<ipython-input-15-5876a08b8638>:3: DeprecationWarning: invalid escape sequence \h
  stri = stri.replace("\\midrule","\hline")
<ipython-input-15-5876a08b8638>:4: DeprecationWarning: invalid escape sequence \h
  stri = stri.replace("{}","\hline")
<ipython-input-15-5876a08b8638>:5: DeprecationWarning: invalid escape sequence \h
  stri = stri.replace("\\bottomrule","\hline\n" )

In [16]:
with open("/home/ekaterina/Documents/002_writing/aumic-flaring-spi-draft/tables/flares.tex", "w") as f:
    f.write(stri)

In [16]:
print(f"Sector 1: {restab[restab.qcs==1].shape[0]} confirmed flares")
print(f"Sector 27: {restab[restab.qcs==27].shape[0]} confirmed flares")

Sector 1: 75 confirmed flares
Sector 27: 114 confirmed flares